import { TRAINING_STATS as STATS } from "../seer-training-core.js";
export const teamLimits = {atk:15,sp_atk:15,def:15,sp_def:15,spd:10,hp:30};
export function trainingTemplate() {
    const statsInputs = (prefix, max, value = 0) => STATS.map(([key, label]) => `<label>${label}${typeof max === "object" ? '<span class="training-bounded-input">' : ""}<input aria-label="${prefix}${label}" data-stat="${key}" type="number" min="0" max="${typeof max === "object" ? max[key] : max}" step="1" value="${value}"${typeof max === "object" ? ` aria-describedby="training-team-limit-${key}"` : ""}>${typeof max === "object" ? `<button type="button" id="training-team-limit-${key}" class="training-input-limit" data-team-fill="${key}" aria-label="將戰隊加成${label}填滿至${max[key]}" title="點擊填滿至 ${max[key]}"><span aria-hidden="true">/ </span><span class="sr-only">上限 </span><span>${max[key]}</span></button></span>` : ""}</label>`).join("");
    return `<div class="training-heading"><div><h2>精靈模擬培養 <span class="training-beta">公測版</span></h2><p>模擬遊戲內培養，不用浪費資源就能模擬數值。</p></div><div class="training-heading-actions"><button type="button" data-export-image>匯出圖片</button></div></div><p data-export-status class="training-hint" role="status" hidden></p>
        <section class="training-card training-equipment-card"><div class="training-equipment-heading"><h3>裝備與稱號</h3><button type="button" class="secondary-button compact-button" data-equipment-presets>常用組合</button></div><div class="training-equipment"><div><h4>套裝</h4><div class="training-suit-selection"><button type="button" data-suit-select>選擇套裝 <span>›</span></button><button type="button" data-suit-remove hidden>卸下</button></div><p class="training-effect" data-effect="suit"></p></div>${[["eye","目鏡"],["title","稱號"]].map(([id, label]) => `<div><h4>${label}</h4><div class="training-suit-selection"><button type="button" data-equipment-select="${id}">選擇${label} <span>›</span></button><button type="button" data-equipment-remove="${id}" hidden>卸下</button></div><p class="training-effect" data-effect="${id}"></p></div>`).join("")}</div></section>
        <div class="training-layout"><section class="training-stage training-card" aria-label="精靈立繪與刻印"><div class="training-pet" hidden><img width="58" height="58" alt=""><div><div class="training-pet-name"><strong></strong><span class="training-level">Lv.100</span></div><p></p></div><button type="button" data-pet-clear aria-label="清除精靈">×</button></div><div class="training-stagebar"><span data-appearance-name>原始外觀</span><div class="training-stage-actions"><button type="button" data-pet-select hidden>更換精靈</button><button type="button" data-skin-select disabled>關聯皮膚</button></div></div><div class="training-art"><img data-training-art hidden alt=""><button type="button" data-art-placeholder aria-label="選擇精靈"><span>＋</span><p>選擇一隻精靈<br>開始模擬培養</p></button></div><div class="training-mintmarks">${[0,1,2].map(i => `<div class="training-mintmark"><button type="button" class="training-mint-slot" data-mint-slot="${i}" aria-label="選擇刻印 ${i+1}"><span class="training-mint-icon">＋</span><strong>選擇刻印</strong><small>刻印 ${i+1}</small></button><button type="button" data-mint-clear="${i}" hidden>卸下</button></div>`).join("")}</div><p class="training-hint training-mint-hint">刻印數值已包含隱藏加成；同系列最多裝備 2 個。</p></section><div class="training-editor">
            <section class="training-card training-results"><div class="training-section-heading"><h3>能力值</h3><div class="training-mode-tabs" role="tablist" aria-label="能力值模式">${[["base","基礎"],["PVE","PVE"],["PVP","PVP"]].map(([mode,label]) => `<button type="button" role="tab" data-result-mode="${mode}" aria-selected="${mode === "PVP"}" class="${mode === "PVP" ? "is-active" : ""}">${label}</button>`).join("")}</div></div><p class="training-result-error" role="status" data-error></p><div class="training-ability-caption"><span data-result-name>尚未選擇精靈</span><span>能力值 / 學習力</span></div><div class="training-ability-grid" data-ev>${STATS.map(([key,label]) => `<div class="training-ability" data-ability="${key}"><span>${label}</span><output data-result="${key}">—</output><span class="training-ev-control"><input aria-label="學習力${label}" data-stat="${key}" type="number" min="0" max="255" step="1" value="0"><button type="button" class="secondary-button" data-ev-fill="${key}" aria-label="補滿${label}學習力" aria-describedby="training-ev-remaining">補滿</button></span></div>`).join("")}</div><div class="training-section-heading training-ev-footer"><span>學習力 <b data-ev-total>0 / 510</b></span><button type="button" data-ev-clear>清空學習力</button></div><p class="training-hint" id="training-ev-remaining" data-ev-remaining role="status"></p><p class="training-hint" data-mode-note>PVP 模式：包含在玩家對戰有效的裝備加成。</p><details class="training-breakdown"><summary>加成來源與計算說明</summary><div data-breakdown></div><p>一般計算順序：基礎能力＋固定加成，再套用套裝百分比並捨去小數。體力上限培養於套裝加成後加入。</p></details></section>


            </div>

        </div><section class="training-card training-profile"><h3>培養設定</h3><div class="training-profile-grid">
            <div class="training-profile-basics"><h4>基本培養</h4><div class="training-basic"><label>個性<select aria-label="個性" data-nature><option value="1">固執 · 攻擊+10%／特攻−10%</option></select></label><label>天賦<span class="training-bounded-input"><input aria-label="天賦" data-iv type="number" min="0" max="31" step="1" value="31"><span class="training-input-limit" aria-hidden="true">/ 31</span></span></label><label>體力上限<span class="training-bounded-input"><input aria-label="體力上限" data-hp-training type="number" min="0" max="20" step="1" value="20"><span class="training-input-limit" aria-hidden="true">/ 20</span></span></label></div><p class="training-nature-note">攻擊+10%、特攻−10%；個性不影響體力。</p></div>
            <div class="training-profile-status"><div class="training-race-heading"><h4>種族值與年費加成</h4><button type="button" class="secondary-button" data-race-picker hidden>切換為覺醒前</button></div><div class="training-race"><select data-race-mode hidden aria-label="種族值版本"><option value="normal">覺醒前</option><option value="advance">神諭覺醒</option></select><p class="training-hint" data-race-status role="status"></p><button type="button" data-race-retry hidden>重試覺醒資料</button><div class="training-race-stats"></div></div><label class="training-year"><input type="checkbox" data-year-bonus>年費加成 <span>全屬性 +10</span></label></div>
            <div class="training-team"><div class="training-team-heading"><h4>戰隊加成</h4><button type="button" class="secondary-button" data-team-fill-all aria-label="填滿全部戰隊加成">全部填滿</button></div><p class="training-hint">點擊上限數字，填滿該項加成。</p><div class="training-stat-inputs" data-extra>${statsInputs("戰隊加成", teamLimits)}</div></div>
        </div></section><p class="training-limit">異能精靈、特殊套裝的例外與戰鬥中條件效果尚未納入。命中、暴擊與減傷不計入六維。</p>
        <dialog class="training-mint-dialog" aria-labelledby="training-mint-title"><div class="training-dialog-heading"><div><h3 id="training-mint-title">選擇刻印</h3><p>使用最大能力值與隱藏加成；同系列最多裝備 2 個。</p></div><button type="button" class="seer-pet-info-close" data-mint-dialog-close aria-label="關閉刻印選擇">×</button></div><div class="training-dialog-filters"><input type="search" aria-label="搜尋刻印" placeholder="刻印名稱或 ID…"><select aria-label="刻印角數"><option value="all">全部角數</option>${[2,3,4,5].map(i => `<option value="${i}">${i} 角</option>`).join("")}</select><select aria-label="刻印系列"><option value="all">全部系列</option></select><select aria-label="刻印排序"><option value="id">ID 由大到小</option><option value="total">能力總和由高到低</option>${STATS.map(([key,label]) => `<option value="${key}">${label}由高到低</option>`).join("")}</select></div><p data-mint-dialog-status role="status"></p><button type="button" data-mint-dialog-retry hidden>重新載入</button><div class="training-dialog-grid"></div><nav class="training-dialog-pagination" aria-label="刻印選擇分頁"><button type="button" data-mint-prev>上一頁</button><span></span><button type="button" data-mint-next>下一頁</button></nav></dialog>
        <p class="training-credit">資料來源：<a href="https://api.seerapi.com/" target="_blank" rel="noopener noreferrer">SeerAPI</a> · <a href="https://www.bilibili.com/read/cv11168267" target="_blank" rel="noopener noreferrer">能力值公式參考</a></p>`;
}
