import { TRAINING_STATS as STATS } from "../seer-training-core.js";
export const teamLimits = {atk:15,sp_atk:15,def:15,sp_def:15,spd:10,hp:30};
export function trainingTemplate() {
    const statsInputs = (prefix, max, value = 0) => STATS.map(([key, label]) => `<label>${label}${typeof max === "object" ? '<span class="training-bounded-input">' : ""}<input aria-label="${prefix}${label}" data-stat="${key}" type="number" min="0" max="${typeof max === "object" ? max[key] : max}" step="1" value="${value}"${typeof max === "object" ? ` aria-describedby="training-team-limit-${key}"` : ""}>${typeof max === "object" ? `<span id="training-team-limit-${key}" class="training-input-limit"><span aria-hidden="true">/ </span><span class="sr-only">上限 </span>${max[key]}</span></span>` : ""}</label>`).join("");
    return `<div class="training-heading"><div><h2>精靈模擬培養 <span class="training-beta">Beta 版</span></h2><p>調整培養與裝備，即時比較 PVE／PVP 能力值。</p><p class="training-ui-notice">本頁面 UI 尚未調整完成，後續將持續改善排版與操作體驗。</p></div><div class="training-heading-actions"><span class="training-level">Lv.100</span><button type="button" data-export-image>匯出圖片</button></div></div><p data-export-status class="training-hint" role="status" hidden></p>
        <div class="training-layout"><section class="training-stage training-card" aria-label="精靈立繪與刻印"><div class="training-stagebar"><span data-appearance-name>原始外觀</span><div class="training-stage-actions"><button type="button" data-pet-select hidden>更換精靈</button><button type="button" data-skin-select disabled>關聯皮膚</button></div></div><div class="training-art"><img data-training-art hidden alt=""><button type="button" data-art-placeholder aria-label="選擇精靈"><span>＋</span><p>選擇一隻精靈<br>開始模擬培養</p></button></div><div class="training-mintmarks">${[0,1,2].map(i => `<div class="training-mintmark"><button type="button" class="training-mint-slot" data-mint-slot="${i}" aria-label="選擇刻印 ${i+1}"><span class="training-mint-icon">＋</span><strong>選擇刻印</strong><small>刻印 ${i+1}</small></button><button type="button" data-mint-clear="${i}" hidden>卸下</button></div>`).join("")}</div><p class="training-hint training-mint-hint">刻印數值已包含隱藏加成；點擊刻印槽選擇。</p>${[0,1,2].map(i => `<details class="training-mint-adjust" data-mint-values="${i}" hidden><summary>刻印 ${i+1} · 調整能力值</summary><div class="training-stat-inputs">${statsInputs(`刻印${i+1}`,9999)}</div><button type="button" data-mint-max="${i}">還原最終值</button></details>`).join("")}</section><div class="training-editor">
            <section class="training-card training-profile">
                <div class="training-pet" hidden><img width="58" height="58" alt=""><div><strong></strong><p></p></div><button type="button" data-pet-clear aria-label="清除精靈">×</button></div>
                <div class="training-race" hidden><label data-race-picker hidden>種族值版本<select aria-label="種族值版本" data-race-mode><option value="normal">覺醒前</option><option value="advance">神諭覺醒</option></select></label><p class="training-hint" data-race-status role="status"></p><button type="button" data-race-retry hidden>重試覺醒資料</button><div class="training-race-stats"></div></div>
                <div class="training-basic"><label>個性<select aria-label="個性" data-nature><option value="">平衡個性（無修正）</option></select></label><label>個體值<input aria-label="個體值" data-iv type="number" min="0" max="31" step="1" value="31"></label><label>體力上限培養<input aria-label="體力上限培養" data-hp-training type="number" min="0" max="20" step="1" value="0"></label></div>
                <p class="training-nature-note">個性不影響體力。</p>
                <label class="training-year"><input type="checkbox" data-year-bonus>年費加成 <span>全能力 +10</span></label>
            </section>
            <section class="training-card training-results"><div class="training-section-heading"><h3>能力值</h3><div class="training-mode-tabs" role="tablist" aria-label="能力值模式">${[["base","基礎"],["PVE","PVE"],["PVP","PVP"]].map(([mode,label]) => `<button type="button" role="tab" data-result-mode="${mode}" aria-selected="${mode === "PVP"}" class="${mode === "PVP" ? "is-active" : ""}">${label}</button>`).join("")}</div></div><p class="training-result-error" role="status" data-error></p><div class="training-ability-caption"><span data-result-name>尚未選擇精靈</span><span>能力值 / 學習力</span></div><div class="training-ability-grid" data-ev>${STATS.map(([key,label]) => `<label class="training-ability" data-ability="${key}"><span>${label}</span><output data-result="${key}">—</output><input aria-label="學習力${label}" data-stat="${key}" type="number" min="0" max="255" step="1" value="0"></label>`).join("")}</div><div class="training-section-heading training-ev-footer"><span>學習力 <b data-ev-total>0 / 510</b></span><button type="button" data-ev-clear>清空學習力</button></div><p class="training-hint" data-mode-note>PVP 模式：包含在玩家對戰有效的裝備加成。</p><details class="training-breakdown"><summary>加成來源與計算說明</summary><div data-breakdown></div><p>一般計算順序：基礎能力＋固定加成，再套用套裝百分比並捨去小數。體力上限培養於套裝加成後加入。</p></details></section>
            <section class="training-card"><h3>裝備與稱號</h3><div class="training-equipment"><div><h4>套裝</h4><div class="training-suit-selection"><button type="button" data-suit-select>選擇套裝 <span>›</span></button><button type="button" data-suit-remove hidden>卸下</button></div><p class="training-effect" data-effect="suit"></p></div>${[["eye","目鏡"],["title","稱號"]].map(([id, label]) => `<div><h4>${label}</h4><div data-picker="${id}"></div><p class="training-effect" data-effect="${id}"></p></div>`).join("")}</div></section>
            <details class="training-card training-advanced"><summary>戰隊加成</summary><p class="training-hint">填入戰隊提供的能力加成；年費加成請使用上方勾選框。</p><div class="training-stat-inputs" data-extra>${statsInputs("戰隊加成", teamLimits)}</div></details>
        </div></div><p class="training-limit">Beta 版採一般滿級公式；異能精靈、特殊套裝的例外與戰鬥中條件效果尚未納入。命中、暴擊與減傷不計入六維。</p>
        <dialog class="training-mint-dialog" aria-labelledby="training-mint-title"><div class="training-dialog-heading"><div><h3 id="training-mint-title">選擇刻印</h3><p>採最大能力值＋隱藏數值，選取後可調整。</p></div><button type="button" data-mint-dialog-close aria-label="關閉刻印選擇">×</button></div><div class="training-dialog-filters"><input type="search" aria-label="搜尋刻印" placeholder="刻印名稱或 ID…"><select aria-label="刻印角數"><option value="all">全部角數</option>${[2,3,4,5].map(i => `<option value="${i}">${i} 角</option>`).join("")}</select><select aria-label="刻印系列"><option value="all">全部系列</option></select></div><p data-mint-dialog-status role="status"></p><button type="button" data-mint-dialog-retry hidden>重新載入</button><div class="training-dialog-grid"></div><nav class="training-dialog-pagination" aria-label="刻印選擇分頁"><button type="button" data-mint-prev>上一頁</button><span></span><button type="button" data-mint-next>下一頁</button></nav></dialog>
        <p class="training-credit">資料來源：<a href="https://api.seerapi.com/" target="_blank" rel="noopener noreferrer">SeerAPI</a> · <a href="https://www.bilibili.com/read/cv11168267" target="_blank" rel="noopener noreferrer">能力值公式參考</a></p>`;
}
